services:
  # Backend API Service
  - type: web
    name: task-manager-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: CORS_ORIGIN
        value: https://task-manager-frontend.onrender.com

  # Frontend Service
  - type: web
    name: task-manager-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://task-manager-api.onrender.com/api
